#!/usr/bin/env node
/**
 * generate-facts.mjs
 * Reads public/metadata.json and derives fun facts for the receptionist,
 * then writes them to src/data/generatedFacts.ts.
 * Runs automatically before `dev` and `build` via package.json scripts.
 */

import { readFileSync, writeFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const metaPath = join(__dirname, "../public/metadata.json");
const outPath = join(__dirname, "../src/data/generatedFacts.ts");

const data = JSON.parse(readFileSync(metaPath, "utf-8"));

const total = data.length;

const legendary = data.filter((d) => d.room === 4);
const rare      = data.filter((d) => d.room === 3);
const uncommon  = data.filter((d) => d.room === 2);
const common    = data.filter((d) => d.room === 1);

const legendaryCount  = legendary.length;
const rareCount       = rare.length;
const uncommonCount   = uncommon.length;
const commonCount     = common.length;

const rarePct     = ((rareCount / total) * 100).toFixed(2);
const uncommonPct = Math.round((uncommonCount / total) * 100);

const rarestNft = data.reduce((best, d) =>
  d.rarity_rank < best.rarity_rank ? d : best, data[0]);
const rarestToken   = rarestNft.token_id;
const rarestScore   = rarestNft.rarity_score;

const topScoreCount = data.filter((d) => d.rarity_score === rarestScore).length;

const maxScore = Math.max(...data.map((d) => d.rarity_score));
const minScore = Math.min(...data.map((d) => d.rarity_score));
const scoreSpread = Math.round(maxScore / minScore);

const top3 = [...data]
  .sort((a, b) => a.rarity_rank - b.rarity_rank)
  .slice(0, 3)
  .map((d) => `#${d.token_id}`)
  .join(", ");

const eliteCount = rareCount + legendaryCount;
const elitePct   = ((eliteCount / total) * 100).toFixed(1);

const facts = [
  `NFT #${rarestToken} holds rank #1 with a rarity score of ${rarestScore} — the crown jewel of the 10K Squad.`,
  `Only ${topScoreCount} of ${total.toLocaleString()} NFTs share the top rarity score of ${rarestScore}, making Legendary pieces just ${((legendaryCount / total) * 100).toFixed(2)}% of the collection.`,
  `The top 3 rarest pieces in the entire collection are ${top3} — look for them deep in the Legendary Vault.`,
  `The Rare gallery holds just ${rareCount} NFTs — only ${rarePct}% of the entire 10K Squad collection.`,
  `${uncommonCount} NFTs earned Uncommon status, roughly ${uncommonPct}% of the collection, displayed in their own museum wing.`,
  `Rarity scores span from ${minScore} to ${maxScore} — a ${scoreSpread}× spread between the most common and rarest pieces.`,
  `All ${commonCount.toLocaleString()} Common NFTs still have unique art — no two 10K Squad pieces are ever the same.`,
  `Combined, Rare and Legendary NFTs make up just ${elitePct}% of the collection — only ${eliteCount} of ${total.toLocaleString()} pieces.`,
];

const out = `// AUTO-GENERATED by scripts/generate-facts.mjs — do not edit by hand.
// Re-run \`pnpm --filter @workspace/museum-3d generate-facts\` to refresh.

export const DERIVED_FACTS = ${JSON.stringify(facts, null, 2)} as const;
`;

writeFileSync(outPath, out, "utf-8");
console.log(`[generate-facts] Wrote ${facts.length} derived facts → src/data/generatedFacts.ts`);
