// AUTO-GENERATED by scripts/generate-facts.mjs — do not edit by hand.
// Re-run `pnpm --filter @workspace/museum-3d generate-facts` to refresh.

export const DERIVED_FACTS = [
  "NFT #2490 holds rank #1 with a rarity score of 303 — the crown jewel of the 10K Squad.",
  "Only 11 of 3,333 NFTs share the top rarity score of 303, making Legendary pieces just 0.33% of the collection.",
  "The top 3 rarest pieces in the entire collection are #2490, #1864, #1602 — look for them deep in the Legendary Vault.",
  "The Rare gallery holds just 55 NFTs — only 1.65% of the entire 10K Squad collection.",
  "300 NFTs earned Uncommon status, roughly 9% of the collection, displayed in their own museum wing.",
  "Rarity scores span from 1.1234 to 303 — a 270× spread between the most common and rarest pieces.",
  "All 2,967 Common NFTs still have unique art — no two 10K Squad pieces are ever the same.",
  "Combined, Rare and Legendary NFTs make up just 2.0% of the collection — only 66 of 3,333 pieces."
] as const;
